const COLORS = [
	"#FC5C54",
	"#FFD95A",
	"#E95D72",
	"#6A87C8",
	"#5FD0F3",
	"#75C06B",
	"#FFDD86",
	"#5FC6D4",
	"#FF949A",
	"#FF8024",
	"#9BA1A4",
	"#EC66FF",
	"#FF8CBC",
	"#FF9A23",
	"#C5DADB",
	"#A8CE63",
	"#71ABFF",
	"#FFE279",
	"#B6B1B6",
	"#FF6780",
	"#A575FF",
	"#4D82FF",
	"#FFB35A",
	"#00FF00",
	"#FF00FF",
	"#00FFFF",
	"#8A2BE2",
	"#D2691E",
	"#FF1493",
	"#FFD700",
	"#4B0082",
	"#7FFF00",
	"#FF6347",
] as const;

export const AVATARS = [
	{ color: COLORS[0], emoji: "🤶" },
	{ color: COLORS[0], emoji: "🎈" },
	{ color: COLORS[0], emoji: "👹" },
	{ color: COLORS[1], emoji: "🤑" },
	{ color: COLORS[1], emoji: "🎉" },
	{ color: COLORS[1], emoji: "🐥" },
	{ color: COLORS[2], emoji: "🐙" },
	{ color: COLORS[3], emoji: "🫐" },
	{ color: COLORS[4], emoji: "🐳" },
	{ color: COLORS[4], emoji: "⛱" },
	{ color: COLORS[5], emoji: "🌲" },
	{ color: COLORS[6], emoji: "🌞" },
	{ color: COLORS[7], emoji: "🐒" },
	{ color: COLORS[8], emoji: "🐵" },
	{ color: COLORS[8], emoji: "🦩" },
	{ color: COLORS[8], emoji: "🍉" },
	{ color: COLORS[8], emoji: "🤯" },
	{ color: COLORS[9], emoji: "🦊" },
	{ color: COLORS[10], emoji: "🐼" },
	{ color: COLORS[11], emoji: "🦄" },
	{ color: COLORS[12], emoji: "🐷" },
	{ color: COLORS[13], emoji: "🐧" },
	{ color: COLORS[14], emoji: "👽" },
	{ color: COLORS[15], emoji: "🐲" },
	{ color: COLORS[15], emoji: "🥦" },
	{ color: COLORS[16], emoji: "🌎" },
	{ color: COLORS[17], emoji: "🍊" },
	{ color: COLORS[17], emoji: "🙀" },
	{ color: COLORS[17], emoji: "🥳" },
	{ color: COLORS[18], emoji: "🐭" },
	{ color: COLORS[19], emoji: "🍣" },
	{ color: COLORS[20], emoji: "👾" },
	{ color: COLORS[21], emoji: "⛵️" },
	{ color: COLORS[22], emoji: "🤠" },
	{ color: COLORS[23], emoji: "🍀" },
	{ color: COLORS[24], emoji: "🍇" },
	{ color: COLORS[25], emoji: "🎨" },
	{ color: COLORS[26], emoji: "🦋" },
	{ color: COLORS[27], emoji: "🍫" },
	{ color: COLORS[28], emoji: "🌸" },
	{ color: COLORS[29], emoji: "🌟" },
	{ color: COLORS[30], emoji: "🐞" },
	{ color: COLORS[31], emoji: "🥝" },
	{ color: COLORS[32], emoji: "🌮" },
	{ color: COLORS[6], emoji: "🍍" },
	{ color: COLORS[10], emoji: "📦" },
	{ color: COLORS[23], emoji: "🍏" },
	{ color: COLORS[9], emoji: "🎳" },
	{ color: COLORS[20], emoji: "💩" },
	{ color: COLORS[11], emoji: "📙" },
	{ color: COLORS[0], emoji: "📵" },
	{ color: COLORS[1], emoji: "🙌" },
	{ color: COLORS[5], emoji: "🐠" },
	{ color: COLORS[7], emoji: "🐇" },
	{ color: COLORS[15], emoji: "🏠" },
	{ color: COLORS[22], emoji: "🅰" },
	{ color: COLORS[18], emoji: "💏" },
	{ color: COLORS[3], emoji: "🕖" },
	{ color: COLORS[27], emoji: "🌗" },
	{ color: COLORS[9], emoji: "🍕" },
	{ color: COLORS[24], emoji: "🚼" },
	{ color: COLORS[12], emoji: "💖" },
	{ color: COLORS[11], emoji: "📄" },
	{ color: COLORS[14], emoji: "💭" },
	{ color: COLORS[3], emoji: "📶" },
	{ color: COLORS[21], emoji: "💍" },
	{ color: COLORS[5], emoji: "🔆" },
	{ color: COLORS[0], emoji: "🎎" },
	{ color: COLORS[25], emoji: "📓" },
	{ color: COLORS[17], emoji: "🔎" },
	{ color: COLORS[22], emoji: "💀" },
	{ color: COLORS[1], emoji: "🕘" },
	{ color: COLORS[13], emoji: "🛀" },
	{ color: COLORS[28], emoji: "🐎" },
	{ color: COLORS[26], emoji: "🍺" },
	{ color: COLORS[24], emoji: "🍑" },
	{ color: COLORS[27], emoji: "👔" },
	{ color: COLORS[29], emoji: "🚔" },
	{ color: COLORS[30], emoji: "💡" },
	{ color: COLORS[31], emoji: "🚒" },
	{ color: COLORS[32], emoji: "💽" },
	{ color: COLORS[4], emoji: "🌵" },
	{ color: COLORS[5], emoji: "🌜" },
	{ color: COLORS[6], emoji: "🐀" },
	{ color: COLORS[7], emoji: "🚸" },
	{ color: COLORS[9], emoji: "🌋" },
	{ color: COLORS[10], emoji: "🕤" },
	{ color: COLORS[11], emoji: "👒" },
	{ color: COLORS[12], emoji: "🐊" },
	{ color: COLORS[13], emoji: "🍟" },
	{ color: COLORS[14], emoji: "🐗" },
	{ color: COLORS[16], emoji: "🍴" },
	{ color: COLORS[17], emoji: "🍌" },
	{ color: COLORS[18], emoji: "🌺" },
	{ color: COLORS[20], emoji: "🚢" },
	{ color: COLORS[22], emoji: "🍙" },
];
export type Avatar = (typeof AVATARS)[number];
